=== DavidRichard2016/SampleRestAssured/src/main/resources/bookResonseSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "rating": {
      "type": "object",
      "properties": {
        "max": {
          "type": "integer"
        },
        "numRaters": {
          "type": "integer"
        },
        "average": {
          "type": "string"
        },
        "min": {
          "type": "integer"
        }
      },
      "required": [
        "max",
        "numRaters",
        "average",
        "min"
      ]
    },
    "subtitle": {
      "type": "string"
    },
    "author": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "pubdate": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "count": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        },
        "required": [
          "count",
          "name",
          "title"
        ]
      }
    },
    "origin_title": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "binding": {
      "type": "string"
    },
    "translator": {
      "type": "array",
      "items": {}
    },
    "catalog": {
      "type": "string"
    },
    "pages": {
      "type": "string"
    },
    "images": {
      "type": "object",
      "properties": {
        "small": {
          "type": "string"
        },
        "large": {
          "type": "string"
        },
        "medium": {
          "type": "string"
        }
      },
      "required": [
        "small",
        "large",
        "medium"
      ]
    },
    "alt": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "publisher": {
      "type": "string"
    },
    "isbn10": {
      "type": "string"
    },
    "isbn13": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "alt_title": {
      "type": "string"
    },
    "author_intro": {
      "type": "string"
    },
    "summary": {
      "type": "string"
    },
    "price": {
      "type": "string"
    }
  },
  "required": [
    "rating",
    "subtitle",
    "author",
    "pubdate",
    "tags",
    "origin_title",
    "image",
    "binding",
    "translator",
    "catalog",
    "pages",
    "images",
    "alt",
    "id",
    "publisher",
    "isbn10",
    "isbn13",
    "title",
    "url",
    "alt_title",
    "author_intro",
    "summary",
    "price"
  ]
}

=== DavidRichard2016/SampleRestAssured/src/main/resources/bookResponse.json
{
  "rating": {
    "max": 10,
    "numRaters": 40,
    "average": "9.5",
    "min": 0
  },
  "subtitle": "",
  "author": [
    "毕淑敏"
  ],
  "pubdate": "2016-11",
  "tags": [
    {
      "count": 35,
      "name": "好书，值得一读",
      "title": "好书，值得一读"
    },
    {
      "count": 30,
      "name": "我想读这本书",
      "title": "我想读这本书"
    },
    {
      "count": 14,
      "name": "治愈系",
      "title": "治愈系"
    },
    {
      "count": 8,
      "name": "生活哲学",
      "title": "生活哲学"
    },
    {
      "count": 8,
      "name": "文学",
      "title": "文学"
    },
    {
      "count": 8,
      "name": "正能量女神",
      "title": "正能量女神"
    },
    {
      "count": 7,
      "name": "想读，一定很精彩！",
      "title": "想读，一定很精彩！"
    },
    {
      "count": 6,
      "name": "想读",
      "title": "想读"
    }
  ],
  "origin_title": "",
  "image": "https://img3.doubanio.com/mpic/s29211875.jpg",
  "binding": "平装",
  "translator": [],
  "catalog": "Chapter_1\n愿你想要的，\n都能自己给自己\n我是怎样度过人生低潮期的？／002\n生命是你自己的，无需别人说三道四／005\n为自己的精神修建三间小屋／010\n人生有三件事不可俭省／015\n最单纯的生活必须品／018\n第二志愿：人生的另一储备／022\n一个人，要学会管住自己／026\n认真策划自己的一生／033\n教养真的不是你读过多少书／039\n你站在金字塔的第几层／043\n每个人内心深处都有一个天真孩童／049\n很多事虽不必躬亲，但要有自己的看法／058\nchapter_2\n愿你自在生长，\n长成自己喜欢的模样\n尊重生活本来的面目，即便泥沙俱下／065\n流露你的真表情／071\n研究真诚／076\n心灵拒绝创可贴／081\n对自己诚实一点／088\n在一张纸上断舍离／091\n凝视崇高／98\n谎言三叶草／103\n抑郁的源头／108\n轰毁你心中的魔床／120\nchapter_3\n愿你一生被爱，\n有枝可依\n你为什么总是遇人不淑／120\n失恋，究竟你失去什么／127\n在爱的过程中，方法不是最重要的／137\n爱不是万能钥匙／141\n关于爱情的奇谈怪论／149\n飘扬的长发与人生的幸福／155\n完美女生／161\n好好爱自己／166\n做自己身体的朋友／167\n生命是朴素的／171\nchapter_4\n愿你想要的都得到，\n得不到的都释怀\n你要知道自己的目标，并尽早实现／176\n提醒幸福／179\n关于爱情与友情的絮语／184\n购买一个希望／187\n有时妥协是为了更好地证明自己／189\n谁都别靠，请自行上路／191\n面对不确定事情，我们只需安静等待／194\n命运没有不公，是你自己太弱／198\n别跟注定失败的事较劲／201\n等待并不一定是最好的选择／205\n我们总是在互相羡慕／210\n世界本就不完美，我们不过顺势而为／213\n堵心的时候别委屈自己／215\n你没有理由不爱自己／220",
  "pages": "240",
  "images": {
    "small": "https://img3.doubanio.com/spic/s29211875.jpg",
    "large": "https://img3.doubanio.com/lpic/s29211875.jpg",
    "medium": "https://img3.doubanio.com/mpic/s29211875.jpg"
  },
  "alt": "https://book.douban.com/subject/26933142/",
  "id": "26933142",
  "publisher": "云南人民出版社",
  "isbn10": "7222152318",
  "isbn13": "9787222152311",
  "title": "让美好现在发生",
  "url": "https://api.douban.com/v2/book/26933142",
  "alt_title": "",
  "author_intro": "毕淑敏：\n★华语世界最具影响力女作家，被王蒙称为“文学界的白衣天使”，以精细、平实的文风和春风化雨般的济世情怀著称，多年来一直深受读者喜爱。\n★国家一级作家，北京作家协会副主席，著名心理咨询师。\n微信公众号“毕淑敏（bishumin_xingfu）”。",
  "summary": "没有人告诉我们生活的真实模样，我们在拼凑来的价值观里寻找人生。有时弄丢自己，有时弄丢爱情，有时弄丢生活，我们渴望过美好生活，有美好的关系，享美好的人生。然而，当我们横在梦与现实之间时，总难两全。甚至习惯把实现它们的时间，放到遥远的将来，觉得当下并不容易实现。\n其实如毕淑敏老师所言：美好并不像很多人想象的那样稀少和昂贵，或者说必须有非常杰出的条件才能达到。美好是一种人人经过努力都可以实现的愿望。\n期待看完这本书的你，能把握让美好发生的所有可能，让自己越来越美好。",
  "price": "35.00"
}
